core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [

    # Main page
    path('',
         views.MainPage.as_view(),
         name='MainPage'),

    # Create track
    path('create_voice/',
         views.CreateMessageView.as_view(),
         name='CreateVoice'),

    # Delete link
    path('<uuid:pk>/delete/',
         views.DeleteMassageView.as_view(),
         name='delete_track'),

    path('api/voice/create/',
         views.VoiceTrackCreateView.as_view(),
         name='create_track'),

    path('api/voice/<uuid:pk>/',
         views.VoiceTrackDetail.as_view(),
         name='detail_track'),

    path('api/voice/list/',
         views.VoiceTrackList.as_view(),
         name='list_track'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import urls
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
import users.views


app_name = 'users'
urlpatterns = [

    url(r'^signup/$', users.views.signup, name='signup'),

    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        users.views.activate, name='activate'),

    path('login/',
         LoginView.as_view(),
         name='login'),

    path('logout/',
         LogoutView.as_view(),
         name='logout'),

    url(r'password_change/$',
        auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html',
                                              success_url='password_change_done/'),
        name='password_change'),

    url(r'password_change_done/',
        auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html')),

    url(r'password_reset/$',
        auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html',
                                             email_template_name='registration/password_reset_email.html',
                                             subject_template_name='registration/password_reset_subject.txt',
                                             success_url='password_reset_done/',
                                             from_email='support@yoursite.ma'),
        name='password_reset'),

    url(r'password_reset_done/',
        auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html')),

    url(r'password_reset_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='registration/password_reset_confirm.html',
            success_url='password_reset_complete/',),
        name='password_reset_confirm'),

    url(r'password_reset_complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html')),

    path('api/login/', users.views.LoginAPIView.as_view(), name='api_login'),

    path('api/balance/', users.views.BalanceAPIView.as_view(), name='api_balance'),

]

voice_project/urls.py
from django.contrib import admin

from django.shortcuts import render, redirect
from django.conf import settings

from django.urls import include, path
import users.urls
import core.urls


urlpatterns = [
    path('', include(core.urls, namespace='core')),

    path('users/', include(users.urls, namespace='user')),

    path('admin/', admin.site.urls),

]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

core/models.py
import uuid
import logging
import random
from django.conf import settings
from django.db import models
from django.db.models import F
from django.contrib.auth import get_user_model
from .client import VoiceGeneratorRpcClient


logger = logging.getLogger(__name__)
# Create your models here.
# Language choices
ENGLISH = 'EN'
LANGUAGES = (
    (ENGLISH, 'English'),
)
# Voice choices
AMANDA = 'AM'
VOICES = (
    (AMANDA, 'Amanda'),
)
# RabbitMQ conf
voice_rpc = VoiceGeneratorRpcClient()


class VoiceTrack(models.Model):

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    created = models.DateTimeField(auto_now_add=True)

    text = models.CharField(max_length=999999)

    owner = models.ForeignKey(to=settings.AUTH_USER_MODEL,
                              on_delete=models.CASCADE,
                              related_name='tracks')

    audio = models.FileField(upload_to='audio/', blank=True)

    duration = models.IntegerField(default=0)

    pitch = models.SmallIntegerField(default=0)

    speed = models.FloatField(default=1)

    language = models.CharField(max_length=2,
                                choices=LANGUAGES,
                                default=ENGLISH,)

    voice = models.CharField(max_length=2,
                             choices=VOICES,
                             default=AMANDA,)

    def __str__(self):

        return self.text[:15]

    def user_have_enough_balance(self, user):
        return len(self.text) <= user.balance

    def user_have_permis(self, user):
        return user == self.owner

    class Meta:
        ordering = ['-created']

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        is_new = self._state.adding or force_insert

        if is_new:
            # Desrising balance of user
            number_of_symbols = len(self.text)
            own = get_user_model().objects.get(id=self.owner.id)
            own.balance = F("balance") - number_of_symbols
            own.save()

            response = voice_rpc.call(self.text)
            self.text = response.decode('utf-8')
            self.duration = random.randint(1, 3)
            super().save(force_insert=force_insert, force_update=force_update,
                         using=using, update_fields=update_fields)

templates/a.html
<!DOCTYPE html>
<html>

<head>
    <title>Audio Test</title>
    <script src="https://unpkg.com/wavesurfer.js"></script>
</head>

<body>
    
	<div id="waveform"></div>

    <script >
    	var wavesurfer = WaveSurfer.create({
		    container: '#waveform',
		    waveColor: 'violet',
		    progressColor: 'purple'
		});

		wavesurfer.load('../voice site/rammstein.mp3');;
    </script>

</body>

</html>

templates/about.html
{% extends "base.html" %}
{% load static %}



{% block title %}
About
{% endblock %}

{% block body %}
<div class="about-frame">
  About
    
</div>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="icon" href="{% static 'image/u.png' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/select-style.css' %}">
    <link rel="stylesheet" href="{% static 'css/range.css' %}">
    <link rel="stylesheet" href="{% static 'css/table.css' %}">
    <link rel="stylesheet" href="{% static 'css/loader.css' %}">
    <link rel="stylesheet" href="{% static 'css/fileup.css' %}">
    <link rel="stylesheet" href="{% static 'css/audio.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="{% static 'js/notify.js' %}"></script>
    {% block style %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <div class="wrap">
        <div class="content">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="logo" onclick="">
                        <a href="{% url "core:MainPage" %}" class="main_page_link">
                            <span class="text-logo">
                                UTTER
                            </span>
                        </a>
                    </div>
                    <div class="menu">
                        <a href="#">PRICE</a>
                        <a href="#">ABOUT</a>
                        {% if request.user.is_authenticated %}
                            <a href="{% url "users:logout" %}">LOGOUT</a>
                        {% else %}
                            <a href="{% url "users:login" %}">LOGIN</a>
                            <a href="{% url "users:signup" %}">SIGNUP</a>
                        {% endif %}

                    </div>
                </div>
            </div>
            {% block body %}
            {% endblock body %}
        </div>

        <div class="footer">
            <span class="email-span">wannafIy@protonmail.com</span>
            <div class="date-foot">
                {% now "Y" as current_year %}
                {% block trans %}Copyright {{ current_year }}
                {% endblock trans %}
            </div>
        </div>
    </div>
    <!--************-->
    <!--************-->
    <!--************-->
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!-- Load using a free CDN -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/wavesurfer.js/1.3.7/wavesurfer.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="{% static 'js/script.js' %}"></script>
    <script src="{% static 'js/audio.js' %}"></script>
</body>

</html>

templates/main.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}

{% block title %}
  Utter
{% endblock %}

{% block body %}
  <!-- INFORMATION -->
    <!--*************-->
    <!--*************-->
    {% if request.user.is_authenticated %}
        <div class="info-panel">
            <div class="welcome-info">
                <div class="auth-token">
                    <div id="copyToken" class="get-token" onclick="copyToken()">Get token</div>
                </div>
                <div class="name-info">
                    <span class="email">{{ request.user.email }}</span>
                </div>
            </div>
            <div class="balance-info">
                <a href="#">
                    <div class="btn-deposit">
                        <span>Deposit</span>
                    </div>
                </a>
                <div class="balance-info-sym"><span class="symbols-balance">{{ request.user.balance }} : symbols</span></div>
            </div>
        </div> 
    {% endif %}
    <!--*************-->
    <!--*************-->
    <!--*************-->
    <!-- TEXT INPUT -->
    <!--*************-->
    <!--*************-->
    <form action="create_voice/" method="post" id="voice_form">
        {% csrf_token %}
        <div class="main-form">
            <div class="text-input">
                {{ form.text }}
                
            </div>
            <div class="settings-input">
                <div class="language-setting">
                    {{ form.language }}
                    
                </div>
                <div class="pitch-setting">
                    <span class="pitch-span">Pitch:</span>
                    <label class="pitch-label" type="text" id="textInput">0</label>
                    <div class="input-pitch">
                        {{ form.pitch }}
                        
                        
                    </div>
                </div>
                <div class="voice-setting">
                    {{ form.voice }}
                    
                </div>
                <div class="speed-setting">
                    <span class="speed-span">Speed:</span>
                    <label class="speed-label" type="text" id="textInput2">1</label>
                    <div class="input-pitch">
                        {{ form.speed }}
                       
                        
                    </div>
                </div>
                <div class="glados-setting">
                </div>
            </div>
            <div class="accept-input">
                <input type="submit" class="btn btn-primary" value="Speek">
                <div class="cssload-bell">
                    <div class="cssload-circle">
                        <div class="cssload-inner"></div>
                    </div>
                    <div class="cssload-circle">
                        <div class="cssload-inner"></div>
                    </div>
                    <div class="cssload-circle">
                        <div class="cssload-inner"></div>
                    </div>
                    <div class="cssload-circle">
                        <div class="cssload-inner"></div>
                    </div>
                    <div class="cssload-circle">
                        <div class="cssload-inner"></div>
                    </div>
                </div>
                <button class="download-input-btn">and download</button>
            </div>
        </div>
    </form>
    <!--*************-->
    <!--*************-->
    <!--*************-->
    <!-- FILE UPLOAD-->
    <!--************-->
    <!--************-->
    <input type="file" name="file-1[]" id="file-1" class="inputfile inputfile-1" style="display:none" accept=".txt,.doc" />
    <label for="file-1" class="btn-dwn"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="17" viewBox="0 0 20 17">
            <path d="M10 0l-5.2 4.9h3.3v5.1h3.8v-5.1h3.3l-5.2-4.9zm9.3 11.5l-3.2-2.1h-2l3.4 2.6h-3.5c-.1 0-.2.1-.2.1l-.8 2.3h-6l-.8-2.2c-.1-.1-.1-.2-.2-.2h-3.6l3.4-2.6h-2l-3.2 2.1c-.4.3-.7 1-.6 1.5l.6 3.1c.1.5.7.9 1.2.9h16.3c.6 0 1.1-.4 1.3-.9l.6-3.1c.1-.5-.2-1.2-.7-1.5z" /></svg> <span>Choose a file&hellip;</span></label>
    <!--************-->
    <!--************-->
    <!--************-->
    <!-- AUDIO PLAYER -->
    <!--**************-->
    <!--**************-->
    <div class="audio-player">
        <div id="audio-spectrum"></div>
        <!-- Create action buttons -->
        <input type="button" id="btn-pause" value="Pause" disabled="disabled" />
        <input type="button" id="btn-play" value="Play" disabled="disabled" />
    </div>
    <!--**************-->
    <!--**************-->
    <!--**************-->
    <!-- FILE TABLE -->
    <!--************-->
    <!--************-->
    {% if request.user.is_authenticated %}
        {% if tracks %}
            <div class="files">
            <table id="customers" align="center">
                <tr >
                    <th>Play</th>
                    <th class="tb-file">Name</th>
                    <th>Duration</th>
                    <th>Date</th>
                    <th>Symbols</th>
                    <th>Language</th>
                    <th>Voice</th>
                    <th>Speed</th>
                    <th>Pitch</th>
                    <th>Download</th>
                    <th class="tb-delete">Delete</th>
                </tr>
                {% for track in tracks %}
                    <tr >
                        <td><img class="play-img" src="{% static 'image/play.png' %}"></td>
                        <td>{{ track }}</td>
                        <td><span>{{ track.duration }}</span></td>
                        <td>{{ track.created | naturalday}}</td>
                        <td>{{ track.text | length}}</td>
                        <td><span>{{ track.get_language_display }}</span></td>
                        <td><span>{{ track.get_voice_display }}</span></td>
                        <td align="center"><span>{{ track.speed }}</span></td>
                        <td align="center"><span>{{ track.pitch }}</span></td>
                        <td><a class="file-ref" href="{% static 'audio/rammstein.mp3' %}" download>
                                <img class="download-img" src="{% static 'image/download-img.png' %}"></a></td>
                        <td><a href="{% url "core:delete_track" pk=track.id %}" class="link_del_track">
                                <img class="delete-img" src="{% static 'image/delete.png' %}"></a></td>
                    </tr>
                
                {% endfor %}
                
            
            </table>
        </div>
        {% endif %}
        
    {% endif %}
    <div class="superinfo"></div>
{% endblock %}

templates/price.html
{% extends "base.html" %}
{% load static %}



{% block title %}
Price
{% endblock %}

{% block body %}
<div class="price-frame">
  Price
    
</div>
{% endblock %}